# Site Settings
title:               世说鑫语
tagline:             学而知不足
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Huang Xin"
  email:             "huanxin694@gmail.com"
  # twitter:           "paululele"
  # instagram:         "paululele"
  github:            "YellowStars1993"
  # facebook:          "Le.Paul.94"
  # linkedin:          "lenpaul"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
#port:                5001
